// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RandomArtsBot.Console")]
[assembly: AssemblyProductAttribute("RandomArtsBot")]
[assembly: AssemblyDescriptionAttribute("Twitter bot for generating random art")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1";
    }
}
